### ISSUE TITLE
[Help] Sign in doesn't work

### ISSUE THREAD

**Issue by VinniciusJesus** [RockyTV/hoymiles-api#1]
I'm trying to login through postman, passing the userName, password as MD5 and a uniqueId but I always get "Incorrect username or password". I'm making requests via the URL https://global.hoymiles.com/permission/system/0/admin/login

**Comment by Xinayder** [comment]
I tried locally with a Solis/Hoymiles account and the URLs have changed. https://global.hoymiles.com no longer works, and using an account from Solis Cloud to login to it doesn't work either.

If you want to login to Solis Cloud, the URL is https://www.soliscloud.com:15555/user/login2 with the following params:

```json
{"userInfo":"your username","passWord":"password md5 hash","yingZhenType":1,"localTimeZone":2,"language":"2"}
```

You can use the following cURL command: 

```
curl -X POST https://www.soliscloud.com:15555/user/login2 \
  -d '{"userInfo":"your username","passWord":"password md5 hash","yingZhenType":1,"localTimeZone":2,"language":"2"}' \
  -H "Content-Type: application/json" 
```

Unfortunately it's been a long time since I last used a Hoymiles inverter and haven't followed with the API changes.

**Comment by VinniciusJesus** [comment]
Do you have any API documentation or something related so that I can update myself and consume Hoymiles data?
